#https://www.codesandnotes.be/2020/01/13/generate-ssh-keys-using-ansible/
- name: Create users
  user:
    name: "{{ item.username }}"
    groups: "{{ class_name }}, rose_students"
    password: "{{ item.username | password_hash('sha512') }}"
    comment: "{{ item.name }}"
    shell: /bin/bash
    append: yes
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: .ssh/{{item.username}}_key
    force: no
    state: present
    update_password: on_create
  register: new_user

# https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server
- name: Allow ssh key auth for user
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ new_user.ssh_public_key }}"


- name: Download privatekey
  fetch:
    src: "{{ new_user.ssh_key_file }}"
    dest: "keys/{{class_name}}/"
    flat: yes